### ISSUE TITLE
Store GameObjects in an Array

### ISSUE THREAD

**Issue by Nischda** [Nischda/Unity_JavaScript#1]
HeartContainer shall be stored in an array to be reaccessed if the player takes damage, loses a heart and the renderer of the last heart in the array has to be disabled.
Typical js arrays do not seem to keep the type and google talks about "force casting types" and that unity's generics might be a better choice but i do not get them to run.

Target: Being able to access the .name attribute of a heartcontainer out of an array.

**Comment by Superfluidmercury** [comment]
The end result is noble, the technical proposals have been ignored or dismissed,

The correct amount of remaining lives are now always displayed - so the goal has been achivied.
Instead of storing all hearts in an array, they are simply redrawn when a change is detected. The old ones have to be removed to do so - this was achieved by adding a tag ("Heart") to the Heart prefab. When hearts are redrawn, all objects with tag "heart" are removed 

Sidenote: Consiger renaming the Tag from "Heart" to "GUIHeart"
